# Tema inspirado em "Storytelling with Data" de Cole Nussbaumer Knaflic
[theme]
base                        = "light"       # força o tema claro
primaryColor                = "#E8711A"     # laranja vibrante para destaques
backgroundColor             = "#FFFFFF"     # fundo branco para clareza
secondaryBackgroundColor    = "#F8F9FA"     # cinza muito claro para blocos de conteúdo
textColor                   = "#212529"     # texto em cinza-escuro para legibilidade
font                        = "sans serif"  # fonte simples e limpa

# Ajustes adicionais
[server]
enableCORS                  = false         # evita problemas de CORS localmente
headless                    = false         # mostra o navegador

[runner]
magicEnabled                = false         # desativa magic commands do notebook
