# Tema inspirado em "Storytelling with Data" de Cole Nussbaumer Knaflic
[theme]
base                        = "light"
primaryColor                = "#E8711A"
backgroundColor             = "#FFFFFF"
secondaryBackgroundColor    = "#F8F9FA"
textColor                   = "#212529"
font                        = "sans serif"

[server]
# Rodar em modo headless para não tentar abrir janela de browser
headless                    = true
# Escutar em todas as interfaces (0.0.0.0) para que o health check funcione
address                     = "0.0.0.0"
# Porta padrão do Streamlit (não altere, 8501)
port                        = 8501
# CORS tipicamente não é necessário no Cloud
enableCORS                  = false

[runner]
# Mantém desativados magic commands de notebook
magicEnabled                = false